CREATE SEQUENCE FUNCIONARIO_SEQ;

CREATE TABLE FUNCIONARIO(
    FUNCIONARIOID NUMERIC(20) NOT NULL,
    NOME VARCHAR(30) NOT NULL,
    CPF VARCHAR(11) NOT NULL,
    TELEFONE VARCHAR(11) NULL,
    EMAIL VARCHAR(30) NOT NULL,
    DATAADMISSAO DATE NOT NULL,
    DEPARTAMENTO VARCHAR(15) NOT NULL,
    SALARIO NUMERIC(11,2) NOT NULL,
    CONSTRAINT PK_FUNCIONARIO PRIMARY KEY (FUNCIONARIOID)
);

CREATE UNIQUE INDEX UN_CPF ON FUNCIONARIO (CPF);
CREATE UNIQUE INDEX UN_EMAIL ON FUNCIONARIO (EMAIL);